# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml




switch:
  - platform: command_line
    switches:
      led_switch:
        command_on: "python3 /config/led2.py on"
        command_off: "python3 /config/led2.py off"
        friendly_name: "LED"
      led_switch2:
        command_on: "python3 /config/led.py on"
        command_off: "python3 /config/led.py off"
        friendly_name: "LED2"

